### ISSUE TITLE
Define - Blocked Words?

### ISSUE THREAD

**Issue by Derpy101** [FlexLabs/Dyno-fun#24]
Not sure if this is an issue, but:
Using the Define Command, currently you can "define" blacklisted or banned words.
It might be a good addition/change to prevent these from being "defined".
This could be an issue for large servers that don't allow inappropriate words.

**Comment by ImCrispyy** [comment]
Or you can just add a automod statement such as. " Sorry...This word(s) is automoded." 
Or actually... ignore that. Why would you be trying to define a word that is already deemed a "bad word" doesn't make sense to make exemption. 🦐

**Comment by CoalSephos** [comment]
Well, even if dyno autodeletes the message the command will still run. May be an idea to just stop commands full stop if a bad word is detected.

**Comment by briantanner** [comment]
No, modules work independently. We wouldn't want to go creating exceptions to rules all over the place for various modules to handle automodded input, etc. use human mods if someone is getting out of control.
